### ISSUE TITLE
Using master as a time capsule

### ISSUE THREAD

**Issue by hhirsch** [convenient/mazeman#6]
"I'd like to keep the master branch as-is, a time-capsule from Spring 2011."

The git mechanism for keeping track of a specific version is tagging. While a lot of people use branches this way I think it just helps to confuse contributors. 

My suggestion is to do:
```
git checkout master;
git tag 0.0.1;
git push origin --tags;
git pull develop;
```

**Comment by convenient** [comment]
Thanks for your comment.

Aye I'm keen on tagging for releases and such like, but to call this repo "active" would be an overstatement. 

Github supports default branches for the main page, AFAIK it does not support default tags. So I'm going to be keeping this as a branch thanks. 

If this was anything near production or anything near sensible I would be doing as you say, but this repo is entirely to have a laugh at some cool shit I wrote when I didn't know any better. 

cheers! 👍
